name: Docker Series Builds

#uncomment to enable push trigger
on: [push]

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     
     - name: docker build csharp
       run: |
         docker build ./c# -t aimvector/csharp:1.0.0
     
    # - name: docker push
    #   run: |
    #     docker push aimvector/csharp:1.0.0
     
