name: Docker Series Builds

#uncomment to enable push trigger
on: [push]

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     
     - name: docker login
       env:
         DOCKER_USER: ${{ secrets.DOCKER_USER }}   
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_REPO }}
       run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

     - name: docker build nodejs
       run: |
         docker build ./nodejs -t sureshhca/csharp_docker_img
     
     - name: docker push
       run: |
             docker push sureshhca/csharp_docker_img
   
      
